### ISSUE TITLE
Use box-drawing characters in Windows.

### ISSUE THREAD

**Issue by Fluffums** [adrian17/jkernel#2]
Do the box-drawing characters "just work" on Linux? Or is there an additional configuration step.

With my Windows installation, the box-drawing characters work fine in JQt, but when I use boxes in Jupyter with the jkernel, I get the `+-|` characters for boxes. This applies to the sample notebook as well when I recalculate the sobel filters in cell 2.

**Comment by adrian17** [comment]
Try the newest version. I won't have access to a Windows machine for a week, but I'm pretty sure I fixed it.

**Comment by Fluffums** [comment]
Success! The force worked.
