### ISSUE TITLE
Explicit definition fails on Windows

### ISSUE THREAD

**Issue by Fluffums** [adrian17/jkernel#5]
(I'm still setting up a Linux virtual machine in order to compare, but I'm betting this has to do with the CR+LF linebreaks in Windows.)

```J
text =: noun define
X
)
```

results in

```J
|value error: X
|syntax error
|   )
```

Similar results to multi-line verb definitions.

**Comment by adrian17** [comment]
This one is easy, I just [haven't implemented multiline input yet (I just return ")" immediately)](https://github.com/adrian17/jkernel/blob/master/wrapper.py#L47). Oops. I should have mentioned that in README. I may try implementing it tomorrow.

**Comment by adrian17** [comment]
Implemented, try it out now.

![screenshot from 2016-02-18 12-41-56](https://cloud.githubusercontent.com/assets/4729533/13142475/9112c3f2-d63d-11e5-91ab-2a613764e19c.png)

**Comment by Fluffums** [comment]
Working well now. Thanks!
